packages:
  - name: contact-form
    environment:
      EMAIL_HOST: "smtp-relay.brevo.com"
      EMAIL_PORT: "587"
      EMAIL_USER: "your_brevo_username"
      EMAIL_PASS: "your_brevo_api_key"
      EMAIL_TO: "recipient@example.com"
    functions:
      - name: contact-form
        runtime: 'nodejs:default'
        main: 'contactForm.js'
        web: true
        limits:
          timeout: 30000
          memory: 256
          logs: 1024
