packages:
  - name: myrixlabs-contact-form
    functions:
      - name: contactForm
        runtime: nodejs:default
        web: true
        source_dir: functions
        parameters:
          EMAIL_HOST: '{{EMAIL_HOST}}'
          EMAIL_PORT: '{{EMAIL_PORT}}'
          EMAIL_USER: '{{EMAIL_USER}}'
          EMAIL_PASS: '{{EMAIL_PASS}}'
          EMAIL_TO: '{{EMAIL_TO}}'
