name: myrixlabs-contact-form
services:
  - name: contact-form-function
    github:
      repo: ranjeetsingh1199/myrixlabs-contact-form-1199
      branch: main
    environment_slug: node-js
    build_command: npm install
    run_command: node functions/contactForm.js
